import Head from 'next/head';

/** 2023/09/18 - 메인 페이지 - by 1-blue */
const Home = () => {
  return (
    <>
      <Head>
        <title>Openknowl</title>

        {/* TODO: */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <h1>Hello, Openknowl</h1>
      </>
    </>
  );
};

export default Home;
