import Head from 'next/head';

import useFetchBoards from '@/hooks/useFetchBoards';

import Board from '@/components/common/Board';

/** 2023/09/18 - 메인 페이지 - by 1-blue */
const Home = () => {
  const { boardsGroup, isLoading, error } = useFetchBoards();

  //! TODO: 각자 컴포넌트 추가하기
  if (!boardsGroup) {
    return <></>;
  }
  if (isLoading) {
    return <></>;
  }
  if (error) {
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Openknowl</title>

        {/* TODO: */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <h1>Hello, Openknowl</h1>

        <Board.Container>
          {boardsGroup.map(boards => (
            <Board.Wrapper
              key={boards[0].category.category}
              droppableId={boards[0].category.category}
              category={boards[0].category.category}
            >
              {boards.map(({ idx, order, ...restProps }) => (
                <Board.Element
                  key={idx}
                  draggableId={idx + ''}
                  index={order}
                  idx={idx}
                  {...restProps}
                />
              ))}
            </Board.Wrapper>
          ))}
        </Board.Container>
      </>
    </>
  );
};

export default Home;
