import Head from 'next/head';

import useFetchBoards from '@/hooks/useFetchBoards';

import { categories } from '@/utils/board';

import Board from '@/components/common/Board';

/** 2023/09/18 - 메인 페이지 - by 1-blue */
const Home = () => {
  const { boards, isLoading, error } = useFetchBoards();

  //! TODO: 각자 컴포넌트 추가하기
  if (!boards) {
    return <></>;
  }
  if (isLoading) {
    return <></>;
  }
  if (error) {
    return <></>;
  }

  // 같은 카테고리끼리 그룹화
  const boardsGroup: { [key: string]: typeof boards } = {};
  boards.forEach(board => {
    boardsGroup[board.category] ?? (boardsGroup[board.category] = []);
    boardsGroup[board.category].push(board);
  });

  return (
    <>
      <Head>
        <title>Openknowl</title>

        {/* TODO: */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <h1>Hello, Openknowl</h1>

        <Board.Container boards={boards}>
          {categories.map(category => (
            <Board.Wrapper key={category} droppableId={category} category={category}>
              {boardsGroup[category].map(({ idx, order, ...restProps }) => (
                <Board.Element
                  key={order}
                  draggableId={idx + ''}
                  index={order}
                  idx={idx}
                  {...restProps}
                />
              ))}
            </Board.Wrapper>
          ))}
        </Board.Container>
      </>
    </>
  );
};

export default Home;
